Εργασία 2
================
Παναγιώτης Δημητρίου
2026-04-08

## ΑΣΚΗΣΗ 1:

(α)

``` r
ask1=function(m,r,x0,n){
  if(r>1 || r< -1){
    stop("Το r θα πρέπει να είναι μεταξύ του -1 και του 1")
  }
  if(n<2 || n%%1!=0){ # n είναι φυσικός (αλλά όχι 1 αφού το υπολογίσαμε πιο κάτω για το x0)
    stop("To n θα πρέπει να είναι φυσικός αριθμός")
  }
x=c() #Δημιουργούμε ένα κενό διάνυσμα x που θα έχει τις τιμές της χρονοσειράς
  
normal=rnorm(n) #Δημιουργούμε ένα τυχαίο δείγμα μεγέθους n απο την N(0,1) 
x[1]=m+r*x0+normal[1] #Υπολογίζουμε την πρώτη τιμή της χρονοσειράς x[1]
                      #με χρήση του x0(δεδομένη τιμή)
for(i in 2:n){ #Υπολογίζουμε τις υπόλοιπες τιμές τις χρονοσειράς 
    x[i]=m+r*x[i-1]+normal[i] #μέσω της δοσμένης αναδρομικής σχέσης
    
  }

return(x)
}
```

(β) (α’)Προσομειώνουμε απο την χρονοσειρά {Xt} για τις ζητούμενες τιμές
με τη χρήση της συνάρτησης ask1 που κατασκευάσαμε.

``` r
set.seed(1)
```

``` r
z1a=ask1(0,-1/2,0,1000)
z2a=ask1(0,0,0,1000)
z3a=ask1(0,1,0,1000)
```

(β’)

``` r
z1b=ask1(2,1/2,3,1000)
z2b=ask1(3,1/2,3,1000)
```

Τώρα δημιουργήσαμε τα 5 διανύσματα μεγέθους 1000 για τις ζητούμενες
παραμέτρους. Θέλουμε να ελέγξουμε αν προέρχονται απο την κανονική
κατανομή.Επομένως, μερικοί τρόποι για να το κάνουμε αυτό είναι μέσω
ιστογράμματος, μη παραμετρικής εκτίμησης (Gaussian Kernel), εμπειρικής
συνάρτησης κατανομής, γραφικού ελέγχου Q-Q plot και του στατιστικού
ελέγχου Lilliefors.

ΙΣΤΟΓΡΑΜΜΑ

``` r
par(mfrow = c(1, 2)) 
hist(z1a,probability=TRUE,main="z1a (r=-0.5)", col="lightblue")
lines(seq(-5,5,0.1),dnorm(seq(-5,5,0.1),mean(z1a),sd=sd(z1a)),col="black",lwd=2)
hist(z2a,probability=TRUE,xlim=c(-5,5), main="z2a (r=0)", col="red")
lines(seq(-5,5,0.1),dnorm(seq(-5,5,0.1),mean(z2a),sd=sd(z2a)),col="black",lwd=2)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

Παρατηρούμε ότι οι δύο πρώτες προσομειώσεις φαίνετε να ακολουθούν την
κανονική κατανομή βλέποντας τις μορφές των ιστογραμμάτων και
συγκρίνοντας με την κανονική κατανομή αφού είναι συμμετρικές με παρόμοια
μορφή με την κανονική

``` r
par(mfrow=c(1,1))
hist(z3a,xlim=c(-30,20),main="z3a (r=1)",probability=TRUE,col="blue")
lines(seq(-30,30,0.01),dnorm(seq(-30,30,0.01),mean(z3a),sd=sd(z3a)),col="black",lwd=2)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->

Αντιθέτως, η z3a με ρ=1 φαίνεται να έχει απόκλιση και ασυμμετρία.

``` r
par(mfrow=c(2,1))
hist(z1b,main="z1b (m=2)",probability="True",col="blue")
lines(seq(-1,12,0.01),dnorm(seq(-1,12,0.01),mean(z1b),sd=sd(z1b)),col="black",lwd=2)
hist(z2b,main="z2b (m=3)",probability="True",col="yellow")
lines(seq(-1,12,0.01),dnorm(seq(-1,12,0.01),mean(z2b),sd=sd(z2b)),col="black",lwd=2)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

Παρομοίως, οι προσομοιώσεις z1b και z2b ($\rho = 0.5$) εμφανίζουν
συμμετρική μορφή που προσεγγίζει ικανοποιητικά την κανονική κατανομή. Η
αλλαγή της παραμέτρου $\mu$ (από 2 σε 3) μετατοπίζει απλώς το κέντρο της
κατανομής.

Τώρα ένας άλλος τρόπος για να δούμε αν το δείγμα μας προέρχεται από την
κανονική είναι μέσω της επίδρασης του Gaussian Kernel για την εκτίμηση
της συνάρτησης πυκνότητας πιθανότητας.

``` r
par(mfrow=c(1,2))
plot(density(z1a),main="Density z1a",col="blue",ylim=c(0,0.4))
lines(seq(-5,5,0.01),dnorm(seq(-5,5,0.01),mean(z1a),sd=sd(z1a)),col="black",lw=1)
plot(density(z2a),main="Density z2a",col="blue")
lines(seq(-5,5,0.01),dnorm(seq(-5,5,0.01),mean(z2a),sd=sd(z2a)),col="black",lw=1)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-8-1.png)<!-- -->

``` r
par(mfrow=c(1,1))
plot(density(z3a),main="Density z3a",col="blue")
lines(seq(-35,35,0.01),dnorm(seq(-35,35,0.01),mean(z3a),sd=sd(z3a)),col="black",lw=1)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->

``` r
par(mfrow=c(1,2))
plot(density(z1b),main="Density z1b",col="blue")
lines(seq(-1,10,0.01),dnorm(seq(-1,10,0.01),mean(z1b),sd=sd(z1b)),col="black",lw=1)
plot(density(z2b),main="Density z2b",col="blue")
lines(seq(0,10,0.01),dnorm(seq(0,10,0.01),mean(z2b),sd=sd(z2b)),col="black",lw=1)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-10-1.png)<!-- -->

Προφανώς σε όλες τις περιπτώσεις εκτός της z3a οι εκτίμηση της σ.μ.π με
τον Gaussian Kernel φαίνεται να είναι πολύ παρόμοια με την αντίστοιχη
συνάρτηση πυκνότητας της κανονικής κατανομής.Επομένως είναι αλλη μια
ένδειξη οτι τα z1a,z2a,z1b,z2b ακολουθούν όντως την κανονική.

Συγκρίνουμε την εμπειρική συνάρτηση κατανομής με τη θεωρητική κανονική
κατανομή με παραμέτρους τη μέση τιμή και την τυπική απόκλιση του
δείγματος.

``` r
par(mfrow=c(1,2))
plot.ecdf(z1a, verticals=TRUE, col.p="white", col.v="black", main="ecdf z1a")
lines(seq(-5,5,0.01),pnorm(seq(-5,5,0.01),mean(z1a),sd=sd(z1a)),col="cyan",lw=1)
plot.ecdf(z2a, verticals=TRUE, col.p="white", col.v="black",main="ecdf z2a")
lines(seq(-5,5,0.01),pnorm(seq(-5,5,0.01),mean(z2a),sd=sd(z2a)),col="pink",lw=1)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->

``` r
par(mfrow=c(1,1))
plot.ecdf(z3a, verticals=TRUE, col.p="white", col.v="black",main="ecdf z3a")
lines(seq(-30,20,0.01),pnorm(seq(-30,20,0.01),mean(z3a),sd=sd(z3a)),col="blue",lw=1)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-12-1.png)<!-- -->

``` r
plot.ecdf(z1b, verticals=TRUE, col.p="white", col.v="black",main="ecdf z1b")
lines(seq(0,12,0.01),pnorm(seq(0,12,0.01),mean(z1b),sd=sd(z1b)),col="pink",lw=1)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-13-1.png)<!-- -->

``` r
plot.ecdf(z2b, verticals=TRUE, col.p="white", col.v="black",main="ecdf z2b")
lines(seq(0,10,0.01),pnorm(seq(0,10,0.01),mean(z2b),sd=sd(z2b)),col="pink",lw=1)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-13-2.png)<!-- -->

Παρατηρούμε ότι και σε αυτόν τον οπτικό έλεγχο η εμπειρική συνάρτηση
κατανομής των δειγμάτων είναι παρόμοια με την θεωρητική συνάρτηση
κατανομής της αντίστοιχης κανονικής εκτός του z3a.Αυτή η μέγιστη κάθετη
απόσταση είναι που θα οδηγήσει στην απόρριψη της κανονικότητας στα
στατιστικά τεστ για την z3a.

Tώρα θα κάνουμε τον γραφικό έλεγχο qqnorm για το κάθε δείγμα
χρονοσειράς.

``` r
qqnorm(z1a)
qqline(z1a, col="red")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-14-1.png)<!-- -->

``` r
qqnorm(z2a)
qqline(z2a, col="red")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-14-2.png)<!-- -->

``` r
qqnorm(z3a)
qqline(z3a, col="red")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-14-3.png)<!-- -->

``` r
qqnorm(z1b)
qqline(z1b, col="red")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-14-4.png)<!-- -->

``` r
qqnorm(z2b)
qqline(z2b, col="red")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-14-5.png)<!-- -->

Είναι προφανές οτι μετά από όλους αυτούς τους γραφικούς ελέγχους πως
φαίνεται οτι μόνο το z3a δεν ακολουθεί την κανονική κατανομή αφού τα
πολλά από τα σημεία δεν είναι κοντά στην ευθεία.Αντιθέτως, στα υπόλοιπα
4 δείγματα της χρονοσειράς, τα σημεία στοιχίζονται ικανοποιητικά πάνω
στη διαγώνιο. Η τελική επιβεβαίωση θα δοθεί μέσω του στατιστικού ελέγχου
Lilliefors. O τυπικός έλεγχος K-S προϋποθέτει ότι οι παράμετροι της
θεωρητικής κατανομής (δηλαδή η μέση τιμή και η διακύμανση) είναι γνωστές
εκ των προτέρων. Στη δική μας περίπτωση, οι παράμετροι αυτές είναι
άγνωστες και εκτιμώνται μέσα από τα ίδια τα δείγματα. Η εφαρμογή του
απλού K-S test με εκτιμημένες παραμέτρους θα καθιστούσε τον έλεγχο
υπερβολικά συντηρητικό. Αντιθέτως, ο έλεγχος Lilliefors αποτελεί
προσαρμοσμένη εκδοχή του K-S για περιπτώσεις άγνωστων παραμέτρων.

``` r
library(nortest)
lillie.test(z1a)
```

    ## 
    ##  Lilliefors (Kolmogorov-Smirnov) normality test
    ## 
    ## data:  z1a
    ## D = 0.016564, p-value = 0.7268

``` r
lillie.test((z2a))
```

    ## 
    ##  Lilliefors (Kolmogorov-Smirnov) normality test
    ## 
    ## data:  (z2a)
    ## D = 0.018634, p-value = 0.5457

``` r
lillie.test((z3a))
```

    ## 
    ##  Lilliefors (Kolmogorov-Smirnov) normality test
    ## 
    ## data:  (z3a)
    ## D = 0.077384, p-value = 1.779e-15

``` r
lillie.test((z1b))
```

    ## 
    ##  Lilliefors (Kolmogorov-Smirnov) normality test
    ## 
    ## data:  (z1b)
    ## D = 0.014839, p-value = 0.8565

``` r
lillie.test((z2b))
```

    ## 
    ##  Lilliefors (Kolmogorov-Smirnov) normality test
    ## 
    ## data:  (z2b)
    ## D = 0.019662, p-value = 0.4579

Παρατηρούμε ότι το p-value είναι αρκετά μεγαλύτερο του 0.05 στα δείγματα
z1a, z2a, z1b και z2b. Επομένως, σε επίπεδο σημαντικότητας α=0.05, η
μηδενική υπόθεση δεν απορρίπτεται και συμπεραίνουμε ότι οι συγκεκριμένες
χρονοσειρές ακολουθούν την κανονική κατανομή. Αντιθέτως, για την
περίπτωση z3a, το p-value είναι πολύ μικρό (p \< 0.05). Συνεπώς,
απορρίπτουμε τη μηδενική υπόθεση ότι ακολουθά δηλαδή την κανονική
κατανομή, επιβεβαιώνοντας στατιστικά ότι δεν ακολουθεί την κανονική
κατανομή. Γενικά τα αποτελέσματα ήταν αναμενόμενα και από την
θεώρια.Αυτό εξηγείται θεωρητικά από το γεγονός ότι για ρ=1 το μοντέλο
AR(1) παύει να είναι στάσιμο και η χρονοσειρά αποκτά μνήμη(αφού τα
αθροίσματα δεν συγκλίνουν) σε αντίθεση με τα άλλα 4 δείγματα
χρονοσειρών(τα αθροίσματα συγκλίνουν).

Για την οπτική και στατιστική σύγκριση, θα μπορούσε να χρησιμοποιηθεί η
συνάρτηση scale() για την τυποποίηση των δεδομένων της προσομοίωσης.
Ωστόσο, η προσέγγιση αυτή είναι στατιστικά ισοδύναμη με την προσαρμογή
της θεωρητικής κανονικής κατανομής στις παραμέτρους του δείγματος όπως
εφαρμόσαμε εμείς.(μέση τιμή μ και τυπική απόκλιση σ)

(γ) Αρχικά υπολογίζουμε την συσχέτιση μεταξύ διαδοχικών τιμών.

``` r
cor_z1a <- cor(z1a[-1], z1a[-length(z1a)])
cor_z1a
```

    ## [1] -0.515866

``` r
cor_z2a <- cor(z2a[-1], z2a[-length(z2a)])
cor_z2a
```

    ## [1] 0.001899343

``` r
cor_z3a <- cor(z3a[-1], z3a[-length(z3a)])
cor_z3a
```

    ## [1] 0.9934979

``` r
cor_z1b <- cor(z1b[-1], z1b[-length(z1b)])
cor_z1b
```

    ## [1] 0.5233988

``` r
cor_z2b <- cor(z2b[-1], z2b[-length(z2b)])
cor_z2b 
```

    ## [1] 0.4865739

Η παράμετρος ρ καθορίζει άμεσα την συσχέτιση.Όταν το $|ρ|$ πλησιάζει τη
μονάδα, η συσχέτιση γίνεται ισχυρή και οι τρέχουσες τιμές εξαρτώνται
σημαντικά από τις προηγούμενες.Όταν $ρ = 0$, η συσχέτιση εκμηδενίζεται
και οι διαδοχικές τιμές και οι διαδοχικές τιμές είναι
ασυσχέτιστες,επειδή οι τιμές προέρχονται από την ίδια κατανομή
(κανονική) και η σειρά δεν έχει μνήμη.

Πέραν της παράμετρου ρ, το n (πλήθος των τιμών) επηρεάζει την συσχέτιση.
Το μέγεθος του δείγματος $n$ επηρεάζει τον υπολογισμό. Σε μεγαλύτερα
δείγματα η υπολογιζόμενη συσχέτιση προσεγγίζει με πολύ μεγάλη ακρίβεια
τη θεωρητική τιμή του $ρ$.Σε μικρότερα δείγματα μπορεί να προκαλέσει
μικρές αποκλίσεις από την πραγματική τιμή (π.χ -0.515866 αντί -0.50)

Σχετικά με το x0 και το μ, η συσχέτιση είναι ανεξάρτητη από
μετατοπίσεις. Αφού το μ απλά μετατοπίζει την χρονοσειρά αλλά η σχέση
μεταξύ δύο βημάτων μένει προφανώς ίδια. Για το x0, αυτό είναι προφανώς
ένα σημείο εκκίνησης και σε μετέπειτα στάδια δεν επηρεάζει καθόλου.

Τώρα θα κατασκεύασουμε τα scatter plots. Θα παρατηρήσουμε οτι το μ, απλά
θα μετατοπίζει και δεν θα αλλάζει η συσχέτιση.

``` r
par(mfrow=c(1,2))
plot(z1a[-length(z1a)], z1a[-1], 
      main = "z1a (ρ = -0.5)", 
      xlab = "X[t-1]", ylab = "X[t]", 
      col = "red",xlim=c(-5,5),ylim=c(-5,5))

plot(z2a[-length(z2a)], z2a[-1], 
      main = "z2a (ρ = 0)", 
      xlab = "X[t-1]", ylab = "X[t]", 

           col = "green",xlim=c(-5,5),ylim=c(-5,5))
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-21-1.png)<!-- -->

``` r
par(mfrow=c(1,1))
plot(z3a[-length(z3a)], z3a[-1], 
      main = "z3a (ρ = 1)", 
      xlab = "X[t-1]", ylab = "X[t]", 
      col = "cyan",xlim=c(-10,10),ylim=c(-10,10))
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-22-1.png)<!-- -->

``` r
plot(z1b[-length(z1b)], z1b[-1], 
      main = "z3a (ρ = 1/2, m=2)", 
      xlab = "X[t-1]", ylab = "X[t]", 
      col = "cyan",xlim=c(-5,10),ylim=c(-5,10))
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-23-1.png)<!-- -->

``` r
plot(z2b[-length(z2b)], z2b[-1], 
      main = "z2b (ρ = 1/2, m=3)", 
      xlab = "X[t-1]", ylab = "X[t]", 
      col = "pink",xlim=c(-5,10),ylim=c(-5,10))
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-23-2.png)<!-- -->

Γενικά στο z1a(ρ = -0.5) είναι ελαφρώς αρνητικά κατηφορικό όπως
αναμέναμε απο την τιμή του ρ. Επιπρόσθετα στο z2a(ρ = 0) οι τιμές είναι
διάσπαρτες, κάτι που δείχνει ότι είναι ασυσχέτιστες, ενώ στο z3a(ρ = 1)
παρατηρείται πολύ ισχυρή θετική γραμμική σχέση, αφού κάθε τιμή εξαρτάται
έντονα από την προηγούμενη. Έτσι τα σημεία συγκεντρώνονται γύρω από
ευθεία με θετική κλίση. Όσο αφορά τις z3a και z3b, έχουμε $ρ = 1/2 > 0$,
επομένως αναμέναμε οι τιμές να βρίσκονται τοποθετημένες σε ευθεία με
θετική κλίση, όμως λόγο του ότι το m = 2 ή 3, οι τιμές απλά
μετατοπίστηκαν προς τα δεξιά.(επηρεάζεται μόνο η θέση) Αποδείξαμε οτι
στην χρονοσειρά πιο πάνω οτι $Ε[Χ] = μ/1-ρ$ άρα για m=2 και 3 και ρ =
1/2 $E[X] = 4$ και $Ε[Χ] = 6$ όπως βλέπουμε στο σχήμα αφού έχουμε
συσσώρευση στα σημεία αυτά.

Ακόμη, ένας περαιτέρω έλεγχος θα ήταν μέσω των συναρτήσεων
συνδιασποράς.Η ACF δείχνει τη συσχέτιση για όλα τα παρελθοντικά βήματα
ταυτόχρονα.

``` r
par(mfrow=c(1,2))
acf(z1a)
acf(z2a)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-24-1.png)<!-- -->

``` r
acf(z3a)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-24-2.png)<!-- -->

``` r
par(mfrow=c(1,2))
acf(z1b)
acf(z2b)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-25-1.png)<!-- -->

Στα γραφήματα ACF των στάσιμων σειρών ($|ρ| < 1$), παρατηρούμε εκθετική
μείωση των συσχετίσεων: στην περίπτωση του $ρ=0.5$ η μείωση είναι ομαλή,
ενώ στο $ρ=-0.5$ παρατηρείται εναλλαγή προσήμων.

Αντίθετα, στην περίπτωση $ρ=0$, $z2a$ όλες οι αυτοσυσχετίσεις (εκτός από
το lag 0) βρίσκονται εντός των ορίων στατιστικής σημαντικότητας,
επιβεβαιώνοντας ότι η σειρά ειναι ασυσχέτιστη με μηδενική μνήμη.

Τέλος, στην περίπτωση $ρ=1$, $z3a$, η ACF μειώνεται με εξαιρετικά αργό
ρυθμό και οι αυτοσυσχετίσεις παραμένουν στατιστικά σημαντικές, γεγονός
που υποδηλώνει την ισχυρή εξάρτηση και τη μη στασιμότητα των δεδομένων.

Η ανάλυση της ACF επιβεβαιώνει ότι η παράμετρος $ρ$ είναι αυτή που
καθορίζει τη δυναμική συμπεριφορά της σειράς.

Όταν $|ρ| < 1$, η σειρά είναι στάσιμη και η ACF συγκλίνει μεταξύ των
μπλε γραμμών. Όταν $ρ=1$, η σειρά χάνει τη στασιμότητά της και η ACF
δείχνει μνήμη. Οι παράμετροι $m$ και $x_0$ δεν επηρεάζουν τη μορφή της
ACF, καθώς η αυτοσυσχέτιση είναι ανεξάρτητη από τη μέση τιμή και το
σημείο εκκίνησης.

## ΑΣΚΗΣΗ 2

Η μεταβλητή Sepal.Length εκφράζει το μήκος του σέπαλου (το εξωτερικό
φύλλο του άνθους) από 150 λουλούδια του είδους Ίριδα (Iris) και
μετριέται σε εκατοστά (cm).

Τα βασικά χαρακτηριστικά των παρατηρήσεων της μπορούμε να τα δούμε
εύκολα μέσω της εντολής summary()

``` r
x=iris
library(moments)
set.seed(1)
xl=x$Sepal.Length
```

``` r
 summary(xl)
```

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##   4.300   5.100   5.800   5.843   6.400   7.900

Αναλύοντας τις παραμέτρους θέσης, διαπιστώνουμε ότι η μέση τιμή της
μεταβλητής Sepal Length είναι 5.843 cm, ενώ η διάμεσος είναι 5.800 cm. Η
μικρή διαφορά μεταξύ τους δείχνει μια γενική συμμετρικότητα με ελαφριά
τάση δεξιάς λοξότητας το οποίο επιβεβαιώνει και η μέση τιμή καθώς είναι
λίγο μεγαλύτερη από την διάμεσο.Επίσης $q 0.25=5.100$ και $q 0.75=6.400$
επομένως το 25% των δεδομένων είναι μικρότερο του 5.100, το 50% είναι
μεταξύ του 5.100 και του 6.400 ενώ το υπόλοιπο 25% είναι μεγαλύτερο του
6.400.

``` r
sum(is.na(iris$Sepal.Length))
```

    ## [1] 0

Πιο πάνω πραγματοποιήθηκε έλεγχος για τυχόν απουσιάζουσες τιμές (Missing
Values / NAs) στο δείγμα της μεταβλητής Sepal Length. Όπως προέκυψε, το
σύνολο δεδομένων είναι πλήρες και δεν απουσιάζει καμία παρατήρηση

``` r
sd(xl)
```

    ## [1] 0.8280661

Σχετικά με τις παραμέτρους εύρους και διασποράς, η τυπική απόκλιση
υπολογίστηκε στα 0.8280661 cm, υποδεικνύοντας ότι ο κύριος όγκος των
παρατηρήσεων είναι σχετικά συγκεντρωμένος γύρω από τη μέση τιμή
+-0.8280661, που σημαίνει ότι τα δεδομένα είναι αρκετά καλά
συγκεντρωμένα γύρω από το κέντρο. Οι τιμές κυμαίνονται από ένα ελάχιστο
(Min) 4.300 cm έως ένα μέγιστο (Max) 7.900 cm με εύρος τιμών
$7.900 - 4.300=3.600$.

``` r
skewness(xl)
```

    ## [1] 0.3117531

``` r
kurtosis(xl)
```

    ## [1] 2.426432

Αρχικά, όσο αφορά την λοξότητα (skewness), αναμένουμε ότι θα παρουσιάζει
μια ελαφριά ασυμμετρία προς τα δεξιά αφού $γ1>0$ αλλά και από τις
προηγούμενες μας παρατηρήσεις.

Επιπλέον, η τιμή της κύρτωσης (kurtosis) είναι περίπου 2.426, δηλαδή
μικρότερη του 3 που αντιστοιχεί στην κανονική κατανομή. Αυτό υποδηλώνει
ότι περιμένουμε η κατανομή να έχει πιο επίπεδη κορυφή και μικρότερη
συγκέντρωση τιμών γύρω από τη μέση τιμή σε σχέση με την κανονική
κατανομή.

Με το ιστόγραμμα και το boxplot θα δούμε ένα περίπου την προσεγγιστική
μορφή της pdf της κατανομής και τα ποσοστημόρια (διάμεσος, τεταρτημόρια
καθώς και την ύπαρξη πιθανών ακραίων τιμών.).

``` r
hist(xl,col="blue")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-31-1.png)<!-- -->

``` r
boxplot(xl,col="grey")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-31-2.png)<!-- -->

Παρατηρούμε οτι η διάμεσος είναι περίπου στο κέντρο του κουτιού και ότι
έχουμε λίγο μεγαλύτερο μήκος δεξιάς ουράς, που επιβεβαιώνει ότι είναι
ελαφρώς δεξιά λοξή.

Γενικά, το δείγμα δείχνει μια γενική συμμετρικότητα, με παραπλήσια μέση
τιμή με τη διάμεσο και σχετικά μικρή διασπορά, χωρίς ακραίες τιμές (από
το boxplot).

Όλες αυτές οι ενδείξεις μας οδηγούν στο να υποθέσουμε οτι η Sepal.Length
έχει κάποια χαρακτηριστικά κανονικής κατανομής αλλά μπορεί να μην την
ακολουθούν όντως. Θα εκτελέσουμε παρακάτω και άλλους ελέγχους για να το
διεκπεραιώσουμε.

Θα τυποποιήσουμε τα στοιχεία του δείγματος μας με την εντολή scale.(για
να την συγκρίνω ευκολότερα με την Ν(0,1))

``` r
sxl=scale(xl)
qqnorm(sxl)
abline(0,1,col="red")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-32-1.png)<!-- -->

Αρκετά σημεία βρίσκονται κοντά στη διαγώνιο, κυρίως στο κέντρο, όμως στα
άκρα παρατηρούνται αποκλίσεις, καθώς κάποια σημεία απομακρύνονται από
αυτήν. Αυτό υποδηλώνει ότι το δείγμα προσεγγίζει την κανονική κατανομή,
αλλά δεν την ακολουθεί αυστηρά.

Επιπλέον, θα δούμε τη μη παραμετρική εκτίμηση της συνάρτησης πυκνότητας
πιθανότητας.

``` r
dsxl=density(sxl)
xdsxl=dsxl$x

plot(dsxl,main="Density estimation of scaled Sepal Length",ylim=c(0,0.5))
lines(xdsxl,dnorm(xdsxl),col="red")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-33-1.png)<!-- -->

Η κατανομή των δεδομένων μας δεν έχει το κλασικό σχήμα της «καμπάνας» με
μία έντονη κεντρική κορυφή. Αντιθέτως, εμφανίζεται πιο πλατιά (επίπεδη
στην κορυφή). Αυτή η έλλειψη μιας καθαρής κεντρικής κορυφής αποτελεί
ισχυρή οπτική ένδειξη ότι η μεταβλητή δεν ακολουθεί αυστηρά την κανονική
κατανομή.”

``` r
plot.ecdf(sxl, verticals=T, col.p="white", col.v="black", main="ECDF of the scaled xl sample")
xs=seq(-3,3,by=0.01)
lines(xs,pnorm(xs),type="l", col = "blue")
legend(1.5,0.32,legend=c("xl", "N(0,1)"),
        col=c("black", "blue"), lty=1, cex=0.8)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-34-1.png)<!-- -->

Όπως παρατηρούμε στο παραπάνω γράφημα, η Εμπειρική Συνάρτηση Κατανομής
ακολουθεί σε γενικές γραμμές τη θεωρητική αθροιστική συνάρτηση κατανομής
της τυπικής κανονικής. Ωστόσο, παρουσιάζει ορατές αποκλίσεις σε διάφορα
σημεία, επιβεβαιώνοντας τις ενδείξεις των προηγούμενων γραφημάτων (Q-Q
plot, Density plot). Επειδή οι στατιστικοί έλεγχοι που ακολουθούν
βασίζονται ακριβώς στην εύρεση της μέγιστης κάθετης απόστασης μεταξύ
αυτών των δύο συναρτήσεων, θα προχωρήσουμε στην εκτέλεση του ελέγχου
Kolmogorov-Smirnov και Lilliefors.

``` r
library(nortest)
ks.test(xl,"pnorm",mean=mean(xl),sd=sd(xl))
```

    ## Warning in ks.test.default(xl, "pnorm", mean = mean(xl), sd = sd(xl)): ties
    ## should not be present for the one-sample Kolmogorov-Smirnov test

    ## 
    ##  Asymptotic one-sample Kolmogorov-Smirnov test
    ## 
    ## data:  xl
    ## D = 0.088654, p-value = 0.1891
    ## alternative hypothesis: two-sided

``` r
lillie.test(xl)
```

    ## 
    ##  Lilliefors (Kolmogorov-Smirnov) normality test
    ## 
    ## data:  xl
    ## D = 0.088654, p-value = 0.005788

Για τον στατιστικό έλεγχο της κανονικότητας εφαρμόστηκαν δύο έλεγχοι: το
απλό Kolmogorov-Smirnov (K-S) και η προσαρμογή Lilliefors.

Το απλό K-S test έδωσε τιμή $p = 0.1891$, ωστόσο χρησιμοποιήσαμε την
μέση τιμη και διασπορά του δείγματος γέγονος που δεν θέλουμε. Άρα,
επειδή η μέση τιμή και η τυπική απόκλιση δεν ήταν γνωστές αλλά
εκτιμήθηκαν από το ίδιο το δείγμα, το K-S test θεωρείται ακατάλληλο.
Έτσι, βασιστήκαμε στο test Lilliefors, το οποίο διορθώνει αυτό το σφάλμα
και το οποίο έχει ως παράμετρους θ=(μ,σ^2). Το τεστ Lilliefors έδωσε
τιμή $p = 0.005788 < 0.05$, οδηγώντας μας στην απόρριψη της μηδενικής
υπόθεσης.

Επομένως, στατιστικά, η μεταβλητή δεν ακολουθεί την κανονική κατανομή,
γεγονός που συμφωνεί με τις οπτικές αποκλίσεις που εντοπίστηκαν στα
γραφήματα. Αυτά τα αποτελέσματα εξηγούν τις διαφορές που είχαμε
παρατηρήσει από τους προηγούμενους μας ελέγχους

## Άσκηση 3

(α)

Γράψτε μία συνάρτηση στην R για να προσομοιώσετε με τη μέθοδο του
αντίστροφου μετασχηματισμού ένα τυχαίο δείγα από την κατανομή F(x) =
x/(x+1) , x∈(0,∞).

Παρατηρούμε από την αθροιστική συνάρτηση κατανομής ότι αφού το x ανήκει
σε διάστημα (υπεραριθμήσιμο πλήθος τιμών) το δείγμα μας θα αποτελείται
από συνεχείς τυχαίες μεταβλητές, επομένως για να προσομοιώσουμε με τη
μέθοδο του αντίστροφου μετασχηματισμού ένα τυχαίο δείγμα, θα βρούμε την
αντιστροφη συνάρτηση $f^{-1}(U) = X$

``` r
f3 = function(n){
  if (n <= 0 || n != as.integer(n))
    stop("Το n πρέπει να είναι ένας θετικός ακέραιος.")
  U = runif(n) #προσωμείωνουμε απο την U(0,1) n τιμές
  X = U / (1 - U) #βρίσκουμε εύκολα τον αντίστροφο και επιστρέφουμε n τιμές με την μέθοδο Α.Μ
  return(X)
}
```

(β)

Αυτή η κατανομή έχει μέση τιμή και διασπορά ίση με το άπειρο.
Προσομοιώστε ένα δείγμα μεγέθους 1000 και στη συνέχεια υπολογείστε τη
μέση τιμή και τη διασπορά του δείγατος. Σχολιάστε τα ευρήματά σας σε
σχέση με τις θεωρητικές τιμές.

``` r
set.seed(45)
sample=f3(1000)
var(sample) 
```

    ## [1] 231295.4

``` r
mean(sample) 
```

    ## [1] 30.50706

``` r
sample2=f3(5000)
mean(sample2)
```

    ## [1] 7.229226

``` r
var(sample2)
```

    ## [1] 3356.382

``` r
sample3=f3(10000)
mean(sample3)
```

    ## [1] 14.98323

``` r
var(sample3)
```

    ## [1] 275924.8

Παρόλο που η θεωρητική μέση τιμή και η διασπορά είναι ίσες με το άπειρο,
οι δειγματικές τιμές που υπολογίζονται στην R είναι πεπερασμένες. Αυτό
είναι λογικό, καθώς προκύπτουν από ένα πεπερασμένο δείγμα $n=1000$ (ή
$5000$). Ωστόσο, ακριβώς επειδή η θεωρητική μέση τιμή και η διασπορά
απειρίζονται, οι δειγματικές εκτιμήσεις είναι εξαιρετικά ασταθείς. Όπως
φαίνεται από τις δοκιμές, ο μέσος όρος και η διασπορά δεν συγκλίνει σε
κάποια σταθερή τιμή καθώς αυξάνεται το μέγεθος του
δείγματος(1000,5000,10000) αλλά ούτε συγκλίνει προς το άπειρο όπως
αναμέναμε θεωρητικά γεγονός που αποδυκνυεί ότι εξαρτάται άμεσα από την
εμφάνιση ακραίων τιμών (outliers).(πχ αν προσώμειωθεί u=0.99999)

(γ)

Συγκρίνετε την εμπειρική συνάρτηση κατανομής με τη θεωρητική.

``` r
Fn=ecdf(sample)
plot(Fn, xlim = c(0, 20), main = "Εμπειρική και θεωρητική συνάρτηση κατανομής",
     xlab = "x", ylab = "F(x)")
curve(x / (x + 1), from = 0, to = 20, add = TRUE, col = "red", lwd = 2)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-39-1.png)<!-- -->

Η εμπειρική συνάρτηση κατανομής προσεγγίζει ικανοποιητικά τη θεωρητική
συνάρτηση $$
F(x)=\frac{x}{x+1}, \quad x>0.
$$ Παρατηρούμε ότι οι δύο καμπύλες είναι κοντά μεταξύ τους, με μικρές
αποκλίσεις, οι οποίες οφείλονται στο πεπερασμένο μέγεθος του δείγματος.

Καθώς όμως αυξάνεται το μέγεθος του δείγματος, η εμπειρική συνάρτηση
κατανομής συγκλίνει ομοιόμορφα προς τη θεωρητική συνάρτηση κατανομής,
προσεγγίζοντάς την ολοένα και καλύτερα.

(ε)

Γράψετε ένα πρόγραμμα για να προσομοιώνει την εκθετική σύμφωνα με τα
αποτελέσματα στο ερώτημα δ), και το οποίο περιέχει επίσης μία εντολή για
να καταγράφει πόσες προσπάθειες χρειάζονται για την αποδοχή.

``` r
my.exp.reject <- function(n,lambda){
  
  if(lambda<=0){ #ελέγχουμε αν λ<=0 το οποίο δεν γίνεται στην εκθετική
    stop("lambda needs to be positive")
  }
  sim.vector = c()
  reps = 0
  
  #υπολογίσαμε το αποτέλεσμα του Μ στο (δ) και επιλέγουμε το κατάλληλο ανάλογα με λ που δίνει ο χρήστης
  
  if(lambda < 2){
    M <- (4 / lambda) * exp(lambda - 2) #αν λ<2
  } else {
    M <- lambda #αν λ>=2
  }
  
  for(j in 1:n){ #θέλουμε δείγμα προσομείωσης μήκους n το οποίο υποβάλει ο χρήστης
    
    
    v <- runif(1) #προσομειώνουμε απο την U(0,1) για να παράξουμε την βοηθητική 
    y <- v/(1-v) # για την g(x) έχουμε αλγόριθμο για να προσωμειώσουμε(Α.Μ) {G(x)=x/(x+1),u=x/(x+1)->x=u/(1-u)} g(x)=G'(x)
    u <- runif(1)
    reps <- reps + 1
    # μετρά το σύνολο τών προσπαθείων και τις αθροίζει ούτως ώστε να ξέρουμε τις συνολικές προσπάθειες n τιμών
    
     while(u > (lambda * exp(-lambda*y)) / (M * (1/(1+y)^2))){ #M= 4*exp(λ-2)/λ αν λ<2 ή Μ=λ αν λ>=2 όπως υπολογίσαμε στο (δ). Όσον u>f(x)/(g(x)*M) προσομειώνουμε μέχρι u<=f(x)/(g(x)*M) και τότε Χ=Υ, όπου Χ=sim.vectorμήκους n.
      v <- runif(1)                 
      y <- v/(1-v)
      
      u <- runif(1)
      reps <- reps + 1
    }
    
    sim.vector[j] <- y #διάνυσμα με τις προσομειώσεις
  }
  
  return(list(sim.vector = sim.vector, no.reps = reps, M = M))#παράγουμε μια λίστα με το προσομειωμένο διάνυσμα,                                                                        επαναλήψεις και το Μ.
}
```

Η συνάρτηση ‘my.exp.reject’ προσομοιώνει τιμές από την εκθετική κατανομή
μέσω της μεθόδου αποδοχής-απόρριψης. Η μεταβλητή `reps` καταγράφει τον
συνολικό αριθμό προσπαθειών που απαιτούνται μέχρι την αποδοχή των n
τιμών.

(στ)

Προσομοιώστε 400 τιμές από την εκθετική κατανομή Exp(λ) για 3
διαφορετικές τιμές του λ. Κάντε γραφήματα των προσομοιωμένων τιμών, και
σχολιάστε την ποιότητα των δειγμάτων σας.

``` r
set.seed(1)
s1=my.exp.reject(400,0.5)
s2=my.exp.reject(400,1)
s3=my.exp.reject(400,3)
par(mfrow = c(1, 3))

hist(s1$sim.vector, probability = TRUE, main = expression(lambda == 0.5),
     xlab = "x")
curve(dexp(x, rate = 0.5), add = TRUE)

hist(s2$sim.vector, probability = TRUE, main = expression(lambda == 1),
     xlab = "x")
curve(dexp(x, rate = 1), add = TRUE)

hist(s3$sim.vector, probability = TRUE, main = expression(lambda == 3),
     xlab = "x")
curve(dexp(x, rate = 3), add = TRUE)
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-41-1.png)<!-- -->

Παρατηρούμε ότι τα ιστογράμματα των προσομοιωμένων τιμών προσεγγίζουν
ικανοποιητικά τις αντίστοιχες θεωρητικές συναρτήσεις πυκνότητας
πιθανότητας της εκθετικής κατανομής για κάθε τιμή του λ.

Για μικρότερες τιμές του λ (π.χ. λ = 0.5), οι παρατηρήσεις είναι πιο
απλωμένες και εμφανίζονται μεγαλύτερες τιμές, λόγω της πιο αργής
εκθετικής φθοράς.

Αντίθετα, για μεγαλύτερες τιμές του λ (π.χ. λ = 3), οι τιμές
συγκεντρώνονται περισσότερο κοντά στο μηδέν, όπως αναμένεται θεωρητικά.

Η ποιότητα των δειγμάτων είναι ικανοποιητική, καθώς οι εμπειρικές
κατανομές ακολουθούν καλά τις θεωρητικές καμπύλες. Οι μικρές αποκλίσεις
οφείλονται στο πεπερασμένο μέγεθος του δείγματος.

``` r
mean(s1$sim.vector)
```

    ## [1] 1.974025

``` r
mean(s2$sim.vector)
```

    ## [1] 1.075838

``` r
mean(s3$sim.vector)
```

    ## [1] 0.33615

Από τις πιο πάνω εντολές επιβεβαιώνουμε την ορθότητα της προσομοίωσης,
αφού Οι δειγματικοί μέσοι είναι κοντά στις θεωρητικές αναμενόμενες τιμές
1/λ.

Συνεχίζουμε, για την ανάλυση της ποιότητας των δειγμάτων με την
μη-παραμετρική εκτιμήτρια για $λ=1/2,λ=1,λ=3$ και βλέπουμε την επίδραση
του πυρήνα στην εκτίμηση της σ.π.π.

``` r
dens1=density(s1$sim.vector)
dens2=density(s2$sim.vector)
dens3=density(s3$sim.vector)
par(mfrow=c(1,3))
plot(dens1, main="Density λ=1/2",ylim=c(0,0.4))
lines(dens1$x,dexp(dens1$x,1/2), col="blue")
plot(dens2, main="Density estimation λ=1",ylim=c(0,0.7))
lines(dens2$x,dexp(dens2$x,1), col="blue")
plot(dens3, main="Density λ=3")
lines(dens3$x,dexp(dens3$x,3), col="blue")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-43-1.png)<!-- -->

Παρατηρούμε οτι το δείγμα μας και για τις τρεις τιμές του λ εκτιμά την
σ.π.π πολύ ικανοποιητικά.Όπως βλέπουμε η μέθοδος μας δίνει και αρνητικές
τιμές τις οποίες γνωρίζουμε ότι δεν μπορεί να πάρει η εκθετική κατανομή
αλλά και η κορυφή της εκτίμησης είναι μικρότερη.

``` r
par(mfrow=c(1,3))
qqplot(qexp(ppoints(10000), rate=1/2), s1$sim.vector,main="qq-plot λ=1/2")
abline(0,1,col="red")
qqplot(qexp(ppoints(10000), rate=1), s2$sim.vector,main="qq-plot λ=1")
abline(0,1,col="red")
qqplot(qexp(ppoints(10000), rate=3), s3$sim.vector,main="qq-plot λ=3")
abline(0,1,col="red")
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-44-1.png)<!-- -->

Τα περισσότερα σημεία βρίσκονται περίπου πάνω στην διαγώνιο(ειδικά στην
αρχή-κέντρο των γραφικών) και στις 3 περιπτώσεις εκτός μερικών σημείων
στα άκρα των γραφικών. Πράγμα που μας οδηγεί ότι έχουμε καλή ποιότητα
δείγματος από την εκθετική με το αντίστοιχο λ.

Τέλος θα κάνουμε τον στατιστικό έλεγχο Kolmogorov-Smirnov.

``` r
ks.test(s1$sim.vector,"pexp",rate=1/2)
```

    ## 
    ##  Asymptotic one-sample Kolmogorov-Smirnov test
    ## 
    ## data:  s1$sim.vector
    ## D = 0.032459, p-value = 0.7933
    ## alternative hypothesis: two-sided

``` r
ks.test(s2$sim.vector,"pexp",rate=1)
```

    ## 
    ##  Asymptotic one-sample Kolmogorov-Smirnov test
    ## 
    ## data:  s2$sim.vector
    ## D = 0.044135, p-value = 0.4171
    ## alternative hypothesis: two-sided

``` r
ks.test(s3$sim.vector,"pexp",rate=3)
```

    ## 
    ##  Asymptotic one-sample Kolmogorov-Smirnov test
    ## 
    ## data:  s3$sim.vector
    ## D = 0.034996, p-value = 0.7114
    ## alternative hypothesis: two-sided

Για τον αυστηρό έλεγχο της ποιότητας του δείγματος, εφαρμόσαμε το
Kolmogorov-Smirnov test. Η μηδενική υπόθεση ($H_0$) ελέγχει αν το δείγμα
προέρχεται από την εκθετική κατανομή. Το αποτέλεσμα του ελέγχου έδωσε
p-value \> 0.05. Συνεπώς, δεν υπάρχει καμία στατιστική ένδειξη για να
απορρίψουμε τη μηδενική υπόθεση ότι το δείγμα ακολουθεί την Exp(λ),
γεγονός που αποδεικνύει την ποιότητα του δείγματος εκθετικής κατανομής
που θέλαμε να προσομειώσουμε και την άριστη λειτουργία του αλγορίθμου
αποδοχής-απόρριψης που κατασκευάσαμε.

(η)

Ελέγξτε κατά πόσο ο αριθμός των επαναλήψεων ακολουθεί την γεωμετρική
κατανομή.

Έστω Ι = \# προσπαθειών μέχρι την πρώτη αποδοχή. Τότε σε κάθε προσπάθεια
είτε θα έχω απόρριψη είτε αποδοχή, με πιθανότητα αποδοχής p που είναι
σταθερή και υπολογίζεται όπως πιο κάτω:

$$
p = P\!\left(U \le \frac{f(Y)}{M g(Y)}\right) $$ και
$$ E(Ι)=\frac{1}{p} , p=\frac{1}{M} 
$$

Άρα κάθε προσπάθεια λειτουργεί σαν μια ανεξάρτητη Bernoulli με επιτυχία
“αποδοχή” και πιθανότητα p.  Επομένως,ο αριθμός I των προσπαθειών μέχρι
την πρώτη αποδοχή ακολουθεί τη γεωμετρική κατανομή με παράμετρο p,
δηλαδή έχουμε ότι: Ι ∼ Geometric(1/Μ) με $Ε(Ι)=Μ$.Δηλαδή ότι ο αριθμός
βημάτων που χρείαζονται για προσομείωση κατά μέσο όρο είναι Μ.

Πάμε να υπολογίσουμε τον συνολικό αριθμό βημάτων που χρειάζονται για ένα
δείγμα μήκους 1000 και λ=1 με την μέθοδο αποδοχής απόρριψης μέσω του
αλγόριθμου που κατασκευάσαμε.

``` r
set.seed(1)
res = my.exp.reject(1000, 1)

n = 1000 #μέγεθος δείγματος
reps = res$no.reps #αριθμός επαναλήψεων που έγιναν για n=1000
meanreps=reps/n #μέσος όρος
M=res$M
```

``` r
reps
```

    ## [1] 1483

``` r
meanreps
```

    ## [1] 1.483

``` r
M
```

    ## [1] 1.471518

Άρα υπολογίσαμε τον μέσο όρο επαναλήψεων που χρειάστηκαν για ένα δείγμα
μεγέθους 1000 και το συγκρίνουμε με το Μ που είναι \$Ε(Ι)=Μ \$ όπως
αναφέραμε προηγουμένως και παρατηρούμε οτι οι δύο τιμές ειναι σχεδόν
ίδιες με αποκλίσεις που οφείλονται στο μέγεθος του δείγματος. Ας
ξανακάνουμε το ίδιο για μεγαλύτερο n.

``` r
res = my.exp.reject(10000, 1)
n = 10000 #μέγεθος δείγματος
reps = res$no.reps #αριθμός επαναλήψεων που έγιναν για n=1000
meanreps=reps/n #μέσος όρος
M=res$M
```

``` r
reps
```

    ## [1] 14755

``` r
meanreps
```

    ## [1] 1.4755

``` r
M
```

    ## [1] 1.471518

Όπως ήταν αναμενόμενο επειδή αυξήσαμε το μέγεθος ο μέσος όρος
επαναλήψεων του αλγόριθμου Α/R που δημιουργήσαμε προσεγγίζει το Μ όπως
αποδείξαμε από την θεωρία. Ο μέσος αριθμός προσπαθειών ανά αποδοχή
προσεγγίζεται από την ποσότητα reps/n. Αφού για τη γεωμετρική κατανομή
ισχύει ότι $E(I) = 1/p=Μ$. Παρατηρούμε ότι $meanreps=reps/n ≈ M$,
γεγονός που φαίνεται ότι επιβεβαιώνει ότι ο αριθμός επαναλήψεων
ακολουθεί γεωμετρική κατανομή.

Για να αποδείξουμε ότι ακολουθεί πράγματι την Γεωμετρική θα πρέπει να
κάνουμε γραφικούς και στατιστικούς ελέγχους.

Τροποποιούμε την my.exp.reject και προσθέτουμε σε αυτή να δημιουργεί ένα
διάνυσμα το οποίο να επιστρέφει πόσες επαναλήψεις χρειάστηκαν για κάθε
ένα ξεχωριστά. Δηλαδή για το δείγμα μεγέθους n=5, το Χ\[1\] χρειάστηκε 2
επαναλήψεις το Χ\[2\] χρειάστηκε 1 επαναληψη κτλ.

``` r
my.exp.reject <- function(n,lambda){
  
  if(lambda<=0){ #ελέγχουμε αν λ<=0 το οποίο δεν γίνεται στην εκθετική
    stop("lambda needs to be positive")
  }
  sim.vector = c()
  reps = 0
  vec=c()
  #υπολογίσαμε το αποτέλεσμα του Μ στο (δ) και επιλέγουμε το κατάλληλο ανάλογα με λ που δίνει ο χρήστης
  
  if(lambda < 2){
    M <- (4 / lambda) * exp(lambda - 2) #αν λ<2
  } else {
    M <- lambda #αν λ>=2
  }
  
  for(j in 1:n){ #θέλουμε δείγμα προσομείωσης μήκους n το οποίο υποβάλει ο χρήστης
    
    count=0
    v <- runif(1) #προσομειώνουμε απο την U(0,1) για να παράξουμε την βοηθητική 
    y <- v/(1-v) # για την g(x) έχουμε αλγόριθμο για να προσωμειώσουμε(Α.Μ) {G(x)=x/(x+1),u=x/(x+1)->x=u/(1-u)} g(x)=G'(x)
    u <- runif(1)
    reps <- reps + 1
    count=count+1
    # μετρά το σύνολο τών προσπαθείων και τις αθροίζει ούτως ώστε να ξέρουμε τις συνολικές προσπάθειες n τιμών
    
     while(u > (lambda * exp(-lambda*y)) / (M * (1/(1+y)^2))){ #M= 4*exp(λ-2)/λ αν λ<2 ή Μ=λ αν λ>=2 όπως υπολογίσαμε στο (δ). Όσον u>f(x)/(g(x)*M) προσομειώνουμε μέχρι u<=f(x)/(g(x)*M) και τότε Χ=Υ, όπου Χ=sim.vectorμήκους n.
      v <- runif(1)                 
      y <- v/(1-v)
      
      u <- runif(1)
      reps <- reps + 1
      count=count+1
    }
    vec[j]=count
    sim.vector[j] <- y #διάνυσμα με τις προσομειώσεις
  }
  
  return(list(sim.vector = sim.vector, no.reps = reps, M = M,triespersample = vec)) # Το διάνυσμα με τις επαναλήψεις ανά δείγμα)) #παράγουμε μια λίστα με το προσομειωμένο διάνυσμα,                                                                        επαναλήψεις,το Μ και ένα διάνυσμα με τις επαναλήψεις μέχρι την αποδοχή κάθε στοιχείου
}
```

Θα εκτελέσουμε γραφικούς ελέγχους όπως ιστόγραμμα, ecdf και τον
στατιστικό έλεγχο chi-square για ένα δείγμα μεγέθους n=1000 και λ=1.
Προφανώς η γεωμετρική κατανομή είναι διακριτή.

``` r
set.seed(1)
res=my.exp.reject(1000,1)
allcounts=res$triespersample #δημιουργούμε διάνυσμα με τις επαναλήψεις που χρειάστηκαν για κάθε στοιχείο
M=res$M
hist(allcounts,probability="TRUE",main = "Έλεγχος Γεωμετρικής Κατανομής", xlab = "Επαναλήψεις",breaks=0.5:(max(allcounts)+0.5)) 
x=1:10
lines(x, dgeom(x - 1, 1/M), col = "red",type="h",lwd = 2)#pdf geom(1/M) με X-1 επειδή η R μόνο τον αριθμό των αποτυχιών πριν συμβεί η πρώτη επιτυχία και όχι μέχρι όπως συνήθως ξέρουμε
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-51-1.png)<!-- -->

Παρατηρόυμε ότι το ιστόγραμμα φαίνεται να ακολουθά την γεωμετρική
κατανομή. Συνεχίζουμε με την ecdf.

``` r
t=0:10
plot(ecdf(allcounts), 
      main = "Έλεγχος: Εμπειρική ECDF vs Θεωρητική CDF", #δημιουργούμαι την ecdf
      xlab = "Αριθμός Επαναλήψεων (I)", 
      col = "blue", lwd = 2)
lines(t,pgeom(t-1,1/M),col="red",type="s") #δημιουργούμαι την θεωριτική συνάρτηση κατανομής της geometry(1/M) 
```

![](Statistical-Data-Analysis-Project%5BR%5D-2-_files/figure-gfm/unnamed-chunk-52-1.png)<!-- -->

Βλέπουμε ότι οι ecdf με την θεωριτική συν. κατανομης της γεωμετρικής
γραφικά είναι σχεδόν ίδιες.

Τέλος θα κάνουμε τον στατιστικό έλεγχο chi-square εφόσον συγκρίνουμε με
διακριτή κατανομή.

``` r
maxiter=max(allcounts) #υπολογίζουμε τον μέγιστο αριθμό επαναλήψεων ούτως ώστε το διάνσυσμα που παράγεται από την εντολή table() να είναι ίδιου μεγέθους με το διάνσυσμα t(το 0 δεν συμπεριλαμβάνεται προφανώς)
t=1:maxiter
t
```

    ## [1] 1 2 3 4 5 6

``` r
maxiter
```

    ## [1] 6

``` r
table(allcounts)
```

    ## allcounts
    ##   1   2   3   4   5   6 
    ## 661 243  60  26   8   2

``` r
dgeom(t-1,1/M)
```

    ## [1] 0.679570457 0.217754451 0.069774959 0.022357958 0.007164150 0.002295605

``` r
chisq.test(table(allcounts), p = dgeom(t-1,1/M), rescale="TRUE") #εκτελούμε το τεστ
```

    ## Warning in chisq.test(table(allcounts), p = dgeom(t - 1, 1/M), rescale =
    ## "TRUE"): Chi-squared approximation may be incorrect

    ## 
    ##  Chi-squared test for given probabilities
    ## 
    ## data:  table(allcounts)
    ## X-squared = 5.5254, df = 5, p-value = 0.3552

Γενικά η geom είναι διακριτή και πάει μέχρι το άπειρο.Άρα, το άθροισμα
των θεωρητικών πιθανοτήτων για τις πεπερασμένες τιμές που εμφανίστηκαν
στο δείγμα μας (π.χ. $I = 1$ έως $5$) είναι μικρότερο από τη μονάδα,
γεγονός που αποτρέπει την ορθή εκτέλεση της συνάρτησης chisq.test της R,
η οποία απαιτεί άθροισμα ακριβώς 1.Επομένως βάζουμε την εντολή rescale.
Όπως αναμέναμε και από την θεωρία df=5 αφού έχουμε κ=6 κατηγορίες.

Εφόσον το p-value \> α=0.05 σημαίνει ότι δεν απορρίπτουμε την μηδενική
υπόθεση σε επίπεδο σημαντικότητας α=0.05 άρα το δείγμα allcounts που
περιέχει τον αριθμό τον επαναλήψεων που χρειάζονται μέχρι την αποδοχή
στην μέθοδο A/R φαίνεται να ακολουθεί την geom(1/M) το οποίο
επιβεβαιώνει και ο στατιστικός έλεγχος.
